# Generated by Django 3.2 on 2022-01-13 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('today_homepage', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
