# Generated by Django 3.2 on 2022-01-26 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('today_homepage', '0002_auto_20220126_2233'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
