# Generated by Django 3.2 on 2022-01-20 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('today_homepage', '0002_delete_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherInfo',
            fields=[
                ('city_name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('pub_data', models.DateField(auto_now_add=True)),
                ('max_temperature', models.FloatField()),
                ('min_temperature', models.FloatField()),
                ('feel_temperature', models.FloatField()),
                ('humidity', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='WeatherWindInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_data', models.DateField(auto_now_add=True)),
                ('wind_speed', models.IntegerField()),
                ('wind_deg', models.IntegerField()),
                ('wind_gust', models.FloatField()),
                ('cityname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='today_homepage.weatherinfo')),
            ],
        ),
    ]
