# Generated by Django 3.2 on 2022-01-20 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('today_homepage', '0003_weatherinfo_weatherwindinfo'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='weatherinfo',
            table='weather_info',
        ),
        migrations.AlterModelTable(
            name='weatherwindinfo',
            table='wind_info',
        ),
    ]
